READ = 1 << 0
WRITE = 1 << 1
DOWNLOAD = 1<< 2
DELETE = 1 << 3
SHARE = 1 << 4
MOVE = 1 << 5
CHANGE_OWNER = 1 << 6
CHANGE_ROLE = 1 << 7

ALL_PERMISSIONS = READ | WRITE | DOWNLOAD | DELETE | SHARE | MOVE | CHANGE_OWNER | CHANGE_ROLE